"use client";
import React, {useState, useEffect} from "react";
import {useTranslations} from "next-intl";
import { generateUniqueId } from "@/services/libAux";

const listPolicyES = [
  "1. Introducción",
  "2. Información que recopilamos",
  "3. Uso de la información",
  "4. Limitaciones de la Información",
  "5. Seguridad de los datos",
  "6. Uso exclusivo con fines educativos",
  "7. Cambios en la política de privacidad",
];
const listPolicyEN = [
  "1. Introduction",
  "2. Information we collect",
  "3. Use of information",
  "4. Limitations of Information",
  "5. Data security",
  "6. Exclusive use for educational purposes",
  "7. Changes to the privacy policy",
];
const listDescriptionsES = [
  "Bienvenido a LiveCoaching. Esta política de privacidad describe cómo recopilamos, usamos y protegemos tu información personal al usar nuestra aplicación, que tiene fines estrictamente estudiantiles y de práctica. Al utilizar nuestra aplicación, aceptas las prácticas descritas en esta política.",
  `En nuestra aplicación, solo recopilamos la información que el usuario proporciona de manera voluntaria. Esto incluye datos como:

  Información de contacto: cuando el usuario se registra o se comunica con la app.
  Datos de uso: como la interacción con el contenido y las preguntas enviadas.`,
  "Los datos proporcionados solo se utilizan para fines internos de funcionamiento de la aplicación y mejora del servicio. LiveCoaching no vende ni comparte tu información con terceros sin tu consentimiento explícito.",
  "La información y consejos proporcionados por la app tienen un propósito exclusivamente informativo. No garantizamos la exactitud ni la validez de los datos proporcionados. Las respuestas generadas por la app pueden ser erróneas o inexactas, por lo que siempre recomendamos validar cualquier decisión importante consultando con un profesional en el área correspondiente.",
  "Nos comprometemos a proteger tu información personal mediante medidas de seguridad adecuadas. Sin embargo, debes tener en cuenta que ningún sistema de transmisión por internet es 100% seguro.",
  "La aplicación LiveCoaching se ofrece con fines exclusivamente estudiantiles y de práctica. No proporciona garantías ni debe ser considerada como un consejo profesional.",
  "Nos reservamos el derecho de modificar esta política de privacidad en cualquier momento. Cualquier cambio será notificado en esta página. Te recomendamos revisar esta política periódicamente.",
];
const listDescriptionsEN = [
  "Welcome to LiveCoaching. This privacy policy describes how we collect, use, and protect your personal information when using our application, which is strictly for educational and practice purposes. By using our application, you agree to the practices described in this policy.",
  `In our application, we only collect information that the user provides voluntarily. This includes data such as:

  Contact information: when the user registers or communicates with the app.
  Usage data: such as interaction with content and submitted questions.`,
  "The data provided is only used for internal purposes of the application's operation and service improvement. LiveCoaching does not sell or share your information with third parties without your explicit consent.",
  "The information and advice provided by the app is for informational purposes only. We do not guarantee the accuracy or validity of the data provided. The responses generated by the app may be wrong or inaccurate, so we always recommend validating any important decision by consulting with a professional in the corresponding area.",
  "We are committed to protecting your personal information through appropriate security measures. However, you should be aware that no internet transmission system is 100% secure.",
  "The LiveCoaching application is offered for educational and practice purposes only. It does not provide guarantees and should not be considered as professional advice.",
  "We reserve the right to modify this privacy policy at any time. Any changes will be notified on this page. We recommend reviewing this policy periodically.",
];

const Privacy = () => {
  const t = useTranslations("Privacy");
  const [langSelected, setLangSelected] = useState<string>(t("lang"));
  const [listPolicy, setListPolicy] = useState(listPolicyES);
  const [listDescriptions, setListDescriptions] = useState(listDescriptionsES);

  useEffect(() => {
    if (langSelected === "es") {
      setListPolicy(listPolicyES);
      setListDescriptions(listDescriptionsES);
    } else {
      setListPolicy(listPolicyEN);
      setListDescriptions(listDescriptionsEN);
    }
  }, [langSelected]);

  useEffect(() => {
    if (t("lang") !== langSelected) {
      setLangSelected(t("lang"));
    }
  }, [t("lang")]);

  return (
    <div>
      <div className="container mx-auto px-4 py-10 text-black dark:text-inherit">
        <h1 className="text-3xl font-bold text-center mb-8 ">
          {t("title")}
        </h1>
        {
          listPolicy.map((item, index) => (
            <section key={generateUniqueId()} className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">{item}</h2>
              <p>{listDescriptions[index]}</p>
            </section>
          ))
        }

        
      </div>
    </div>
  );
};

export default Privacy;

/*
1. Introducción

Bienvenido a LiveCoaching. Esta política de privacidad describe cómo recopilamos, usamos y protegemos tu información personal al usar nuestra aplicación, que tiene fines estrictamente estudiantiles y de práctica. Al utilizar nuestra aplicación, aceptas las prácticas descritas en esta política.

2. Información que recopilamos

En nuestra aplicación, solo recopilamos la información que el usuario proporciona de manera voluntaria. Esto incluye datos como:

Información de contacto: cuando el usuario se registra o se comunica con la app.
Datos de uso: como la interacción con el contenido y las preguntas enviadas.

3. Uso de la información

Los datos proporcionados solo se utilizan para fines internos de funcionamiento de la aplicación y mejora del servicio. LiveCoaching no vende ni comparte tu información con terceros sin tu consentimiento explícito.

4. Limitaciones de la Información

La información y consejos proporcionados por la app tienen un propósito exclusivamente informativo. No garantizamos la exactitud ni la validez de los datos proporcionados. Las respuestas generadas por la app pueden ser erróneas o inexactas, por lo que siempre recomendamos validar cualquier decisión importante consultando con un profesional en el área correspondiente.

5. Seguridad de los datos

Nos comprometemos a proteger tu información personal mediante medidas de seguridad adecuadas. Sin embargo, debes tener en cuenta que ningún sistema de transmisión por internet es 100% seguro.

6. Uso exclusivo con fines educativos

La aplicación LiveCoaching se ofrece con fines exclusivamente estudiantiles y de práctica. No proporciona garantías ni debe ser considerada como un consejo profesional.

7. Cambios en la política de privacidad

Nos reservamos el derecho de modificar esta política de privacidad en cualquier momento. Cualquier cambio será notificado en esta página. Te recomendamos revisar esta política periódicamente.
*/
